launch-qemu: log categories argument

diff --git a/bin/launch-qemu b/bin/launch-qemu
--- a/bin/launch-qemu
+++ b/bin/launch-qemu
@@ -32,12 +32,13 @@ trap finish EXIT
 
 function usage()
 {
-    echo "Usage: $0 [-hSq] [-d dt_file] [-e env]* [-m mem] [-n netcfg [-p port]*] [ cmd ]" 1>&2
+    echo "Usage: $0 [-hSq] [-d dt_file] [-e env]*  [-l categories] [-m mem] [-n netcfg [-p port]*] [ cmd ]" 1>&2
     echo "               cmd: command" 1>&2
     echo "                    run - start emulation (default)" 1>&2
     echo "                    gdb - launch the emulator in GDB" 1>&2
     echo "               -d dt_file: Qemu device tree file that defines the machine" 1>&2
     echo "               -e env: load environment settings from file" 1>&2
+    echo "               -l categories: comma-separated categories to log in Qemu log (e.g. "asm_in,int") " 1>&2
     echo "               -m memory map: preload files into memory" 1>&2
     echo "               -n netcfg : choose networking configuration" 1>&2
     echo "                   user: forward a port on the host to the target NIC" 1>&2
@@ -237,9 +238,10 @@ MONITOR=1
 FWD_PORTS=()
 MEMORY_FILES=()
 ENV_FILES=("${PWD}/qemu-env.sh")
+LOG_CATEGORIES="fdt,guest_errors,unimp,cpu_reset"
 
 # parse options
-while getopts "h?S?q?e:d:m:p:n:" o; do
+while getopts "h?S?q?e:d:l:m:p:n:" o; do
     case "${o}" in
         S)
             RESET=0
@@ -252,6 +254,9 @@ while getopts "h?S?q?e:d:m:p:n:" o; do
             ;;
         p)
             FWD_PORTS+=("$OPTARG")
+            ;;
+        l)
+            LOG_CATEGORIES+=",$OPTARG"
             ;;
         m)
             MEMORY_FILES+=("$OPTARG")
@@ -435,8 +440,6 @@ fi
 #
 # See QEMU User Guide in HPSC release for explanation of the command line arguments
 # Note: order of -device args may matter, must load ATF last, because loader also sets PC
-# Note: If you want to see instructions and exceptions at a large performance cost, then add
-# "in_asm,int" to the list of categories in -d.
 
 SERIAL_PORT_ARGS=()
 for _ in "${SERIAL_PORTS[@]}"
@@ -461,7 +464,7 @@ COMMAND=("${GDB_ARGS[@]}" "qemu-system-aarch64"
     -nographic
     -qmp "telnet::$QMP_PORT,server,nowait"
     -S
-    -D "${LOG_FILE}" -d "fdt,guest_errors,unimp,cpu_reset"
+    -D "${LOG_FILE}" -d "$LOG_CATEGORIES"
     -hw-dtb "${QEMU_DT_FILE}"
     "${SERIAL_PORT_ARGS[@]}"
     "${DRIVE_ARGS[@]}"
